[package]
name = "info_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
petgraph = "0.6.2"
uuid = "1.1.2"
itertools = "0.10.5"